In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["Aditya", "Rahul", "Priya"],
    "Age": [28, 32, 25],
    "Salary": [100000, 120000, 90000]
})

In [3]:
df

     Name  Age  Salary
0  Aditya   28  100000
1   Rahul   32  120000
2   Priya   25   90000

In [4]:
df['Salary']

0    100000
1    120000
2     90000
Name: Salary, dtype: int64

In [6]:
df[['Age','Salary']]

   Age  Salary
0   28  100000
1   32  120000
2   25   90000

In [7]:
df['Age'] > 30

0    False
1     True
2    False
Name: Age, dtype: bool

In [8]:
df[df['Age'] > 30]

    Name  Age  Salary
1  Rahul   32  120000

In [9]:
df.sort_values(
    by="Salary",
    ascending=False
)

     Name  Age  Salary
1   Rahul   32  120000
0  Aditya   28  100000
2   Priya   25   90000

In [10]:
df["Salary"].mean()

np.float64(103333.33333333333)

In [11]:
df["Salary"].max()

np.int64(120000)

In [12]:
df["Salary"].min()

np.int64(90000)

In [13]:
df.groupby("Department")[
    "Salary"
].mean()

KeyError: 'Department'